classDiagram
    class Pista {
        -String numero_identificativo
        -int max_capacidad

        +crear()
    }

    class Cliente {
        -int num_cliente
        -String Nombre
        -String direccion
        -int num_telefono
        -email correo
        -pedidos listapedidos

        +crear()
        +hacerReserva()
    }

    class Reserva {
        -Date dia_reserva
        -Time hora_reserva

        +crear()
        +mostrar()
        +calcularCostoTotal()
        +cobrarCostoTotal()
    }

    class Cafeteria {
        -String nombre
        -String descripcion
        -int precio

        +crear()
        +mostrar()
    }

    class Pedido {
        -String descripcion
        -pedidos listapedidos
        -datetime hora

        +crear()
        +cancelar()
        +registrarpedido()
    }

    class DetallePedido {
        -Reserva reserva
        -Pedido pedido
        -String descripcion

        +crear()
    }

    class Partida {
        -String identificador_unico
        -String descripcion
        -int cant_jugadores
        -int puntaje_jugadores
        
        +crear()
        +calcularPuntajeTotal()
    }

    class Jugador {
        -String identificador_unico
        -String nombre
        -turnos listaturnos

        +crear()
    }

    class Turno {
        -String descripcion
        -oportunidad listaoportunidades

        +crear()
        +Calcularpinostotales()
    }

    class Oportunidad {
        -String descripcion
        -int pinos_derribados

        +crear()    
    }

Cliente --> Reserva
Cliente --> Pedido

Reserva --> Pista
Reserva --> Partida
Reserva --> DetallePedido

Pedido --> DetallePedido

Cafeteria --> Pedido

Partida --> Turno 
Turno --> Oportunidad

Jugador --> Partida



