:::mermaid
classDiagram
   class CentroBowling{
        String Nombre
        String Direccion
    }
    class PistaBowling{
        String Pista
        String CapacidadMaxJugadores
    }
    class Cliente{
        String Cliente
        String Nombre
        String Direccion
        String CorreoElectronico
        + ReservaPista()
        + PedidosCafeteria()
    }
    class Cafetería{
        String Nombre
        String Descripcion
        + OfrecePlatos()
        + OfreceBebidas()
    }
    class Plato{
        String Nombre
        String Descripcion
        String Precio
    }
    class Bebida{
        String Nombre
        String Descripcion
        int Precio
    }
    class ReservaPista{
        date Dia 
        date Hora
        + RegistraPedidosCafeteria()
        + RegistraPartidas()
    }
    class Partida{
        String Partida
    }
    class Jugador{
        String ugador
        String Nombre
        + RegistrarPuntaje
    }
    class Turno{
        + RegistrarPuntaje()
    }
  CentroBowling --> "1" PistaBowling
  CentroBowling --> "1..*" Cafetería
  Cliente --> "1..*" ReservaPista
  Cliente --> "1..*" Partida
  Cafetería --> "1..*" Plato
  Cafetería --> "1..*" Bebida
  ReservaPista --> "1" PistaBowling
  ReservaPista --> "1" Partida
  ReservaPista --> "1..*" Cliente
  Partida --> "1..*" Jugador
  Partida --> "1" Turno
  Jugador --> "1..*" Turno