# Generated by Django 5.0 on 2023-12-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroDeBowling', '0002_reserva_cant_personas_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntaje',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
