# Generated by Django 4.2.4 on 2023-12-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentroDeBowling', '0003_puntaje_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleTurno',
        ),
        migrations.RemoveField(
            model_name='fila',
            name='listaturnos',
        ),
        migrations.DeleteModel(
            name='Partida',
        ),
        migrations.DeleteModel(
            name='Pista',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='listatiradas',
        ),
        migrations.DeleteModel(
            name='Fila',
        ),
        migrations.DeleteModel(
            name='Tirada',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
